/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 door_new.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/door_new.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-44.744, 108.093, 10.528]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <group position={[0.002, 0.004, 0]}>
          <mesh geometry={nodes.Plane001_Door_0.geometry} material={materials['Door.006']} position={[0.008, 0, -0.832]} />
          <mesh geometry={nodes.Plane001_Glossy_0.geometry} material={materials['Glossy.004']} position={[0.008, 0, -0.832]} />
          <mesh geometry={nodes.Circle002_Glossy_0.geometry} material={materials['Glossy.004']} position={[0.818, 0.043, -0.029]} />
          <mesh geometry={nodes.Plane003_Door_0.geometry} material={materials['Door.006']} position={[0.86, 0.017, -0.05]} />
        </group>
        <mesh geometry={nodes.Plane002_Door_0.geometry} material={materials['Door.006']} position={[-0.02, 0.005, 0]} />
        <mesh geometry={nodes.Plane002_Glossy_0.geometry} material={materials['Glossy.004']} position={[0.445, 0.105, -1.081]} />
      </group>
    </group>
  )
}

useGLTF.preload('/door_new.glb')
