/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 abandoned_warehouse.glb 
Author: Arsen Ismailov (https://sketchfab.com/fdgasd7)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/abandoned-warehouse-698a34300af34095ac6593f348585daa
Title: Abandoned Warehouse
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Warehouse() {
  const { nodes, materials }:any = useGLTF('/abandoned_warehouse.glb')
  return (
    <group  dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.751}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Roof_Walkway_0.geometry} material={materials.Walkway} />
            <mesh geometry={nodes.Roof_rusty_metal_plate_corrugated_0.geometry} material={materials.rusty_metal_plate_corrugated} />
          </group>
          <group position={[-794.13, 772.632, -1638.689]} rotation={[Math.PI / 2, -1.287, -1.571]} scale={[-108.958, 100, 118.43]}>
            <mesh geometry={nodes.Windows_WarehouseWindow_0.geometry} material={materials.WarehouseWindow} />
            <mesh geometry={nodes.Windows_WarehouseWindow_0_1.geometry} material={materials.WarehouseWindow} />
          </group>
          <group position={[416.95, 440.009, 1727.363]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Office_Office_Floor_0.geometry} material={materials.Office_Floor} />
            <mesh geometry={nodes.Office_MetalRusted_0.geometry} material={materials.MetalRusted} />
            <mesh geometry={nodes.Office_factory_wall_0.geometry} material={materials.factory_wall} />
          </group>
          <group position={[0, 443.379, 1878.638]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Walkway001_MetalRusted_0.geometry} material={materials.MetalRusted} />
            <mesh geometry={nodes.Walkway001_MetalWalkway_0.geometry} material={materials.MetalWalkway} />
          </group>
          <group position={[-2019.269, 94.983, 564.293]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.SmallGateVar3_GateRail_0.geometry} material={materials.GateRail} />
            <mesh geometry={nodes.SmallGateVar3_Rubber_0.geometry} material={materials.Rubber} />
          </group>
          <group position={[-1445.953, 210.66, 564.293]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.SmallGateVar2_GateRail_0.geometry} material={materials.GateRail} />
            <mesh geometry={nodes.SmallGateVar2_Rubber_0.geometry} material={materials.Rubber} />
          </group>
          <group position={[-2589.989, 275.939, 564.293]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.SmallGateVar1_GateRail_0.geometry} material={materials.GateRail} />
            <mesh geometry={nodes.SmallGateVar1_Rubber_0.geometry} material={materials.Rubber} />
          </group>
          <group position={[428.201, 0, -1992.236]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.MainGate001_GateRail_0.geometry} material={materials.GateRail} />
            <mesh geometry={nodes.MainGate001_Rubber_0.geometry} material={materials.Rubber} />
          </group>
          <mesh geometry={nodes.MainSupportBeam_Walkway_0.geometry} material={materials.Walkway} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.cable_Rubber_0.geometry} material={materials.Rubber} position={[343.924, 802.964, -1004.738]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.WarehouseWalls_factory_wall_0.geometry} material={materials.factory_wall} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.SideSupportBeam_Walkway_0.geometry} material={materials.Walkway} position={[990.027, 0, -1997.227]} rotation={[-Math.PI / 2, 0, 0]} scale={[134.792, 100, 100]} />
          <mesh geometry={nodes.Floor_WarehouseMainConcrete_0.geometry} material={materials.WarehouseMainConcrete} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.WarehouseBase_WarehouseMainConcrete_0.geometry} material={materials.WarehouseMainConcrete} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Door2004_DoorMetal_0.geometry} material={materials.DoorMetal} position={[-897.269, 108.585, -1989.766]} rotation={[-Math.PI / 2, 0, -2.752]} scale={100} />
          <mesh geometry={nodes.Door2003_DoorMetal_0.geometry} material={materials.DoorMetal} position={[-715.221, 108.585, -1989.715]} rotation={[-Math.PI / 2, 0, -1.291]} scale={100} />
          <mesh geometry={nodes.Door2002_DoorMetal_0.geometry} material={materials.DoorMetal} position={[-806.341, 202.801, -1993.06]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Door2001_DoorMetal_0.geometry} material={materials.DoorMetal} position={[-989.725, 9.599, -1663.571]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Door2_DoorMetal_0.geometry} material={materials.DoorMetal} position={[-993.07, 4.485, -1622.206]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Door2005_DoorMetal_0.geometry} material={materials.DoorMetal} position={[-985.89, 108.585, 95.073]} rotation={[-Math.PI / 2, 0, -1.667]} scale={100} />
          <mesh geometry={nodes.Door2006_DoorMetal_0.geometry} material={materials.DoorMetal} position={[-985.839, 108.585, -86.975]} rotation={[-Math.PI / 2, 0, 1.803]} scale={100} />
          <mesh geometry={nodes.Door2007_DoorMetal_0.geometry} material={materials.DoorMetal} position={[-989.184, 202.801, 4.145]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes.Door2008_DoorMetal_0.geometry} material={materials.DoorMetal} position={[-2872.671, 110.542, 1596.181]} rotation={[-1.571, 0, -1.573]} scale={[100.459, 100, 100.378]} />
          <mesh geometry={nodes.Door2009_DoorMetal_0.geometry} material={materials.DoorMetal} position={[-2872.619, 110.542, 1413.297]} rotation={[-1.573, 0.001, 0.72]} scale={[100.2, 100.26, 100.378]} />
          <mesh geometry={nodes.Door2010_DoorMetal_0.geometry} material={materials.DoorMetal} position={[-2875.965, 205.114, 1504.836]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[100.459, 100, 100.378]} />
          <mesh geometry={nodes.Railings_MetalRusted_0.geometry} material={materials.MetalRusted} position={[-726.487, 150.136, -2167.416]} rotation={[-Math.PI / 2, 0, 0]} scale={[-100, 100, 100]} />
          <mesh geometry={nodes.ConcreteSteps_WarehouseMainConcrete_0.geometry} material={materials.WarehouseMainConcrete} position={[-785.813, 0, -293.063]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
          <mesh geometry={nodes.Door2011_DoorMetal_0.geometry} material={materials.DoorMetal} position={[-149.004, 467.554, 2115.241]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Door2012_DoorMetal_0.geometry} material={materials.DoorMetal} position={[-152.349, 462.44, 2156.606]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.OfficeDoor_OfficeDoorMaterial_0.geometry} material={materials.OfficeDoorMaterial} position={[-151.091, 473.368, 1465]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.OfficeWindows_OfficeWindow_0.geometry} material={materials.OfficeWindow} position={[-151.66, 574.535, 1801.217]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.OfficeDoor001_OfficeDoorMaterial_0.geometry} material={materials.OfficeDoorMaterial} position={[-148.913, 473.535, 1503.66]} rotation={[-Math.PI / 2, 0, -0.433]} scale={100} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/abandoned_warehouse.glb')
