/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 backrooms_another_level.glb 
Author: Huuxloc (https://sketchfab.com/rjh41)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/backrooms-another-level-429f3c9ea8024f5e9bb78f6649c7bd26
Title: Backrooms Another Level
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Backrooms() {
  const { nodes, materials }:any = useGLTF('/backrooms_another_level.glb')
  return (
    <group dispose={null}>
      <group position={[-15.538, -0.002, -19.259]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.158, 1.327, 1.504]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[11.4, 2.978, 3.831]}>
            <mesh geometry={nodes.Object_12.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Object_13.geometry} material={materials['Material.004']} />
          </group>
          <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Object_6.geometry} material={materials['Material.002']} position={[24.65, 1.497, -1.926]} />
          <mesh geometry={nodes.Object_21.geometry} material={materials['Material.002']} position={[5.966, 1.627, 5.94]} />
          <mesh geometry={nodes.Object_23.geometry} material={materials['Material.002']} position={[8.421, 1.681, 21.719]} />
          <mesh geometry={nodes.Object_19.geometry} material={materials['Material.002']} position={[6.195, 1.505, 3.935]} />
        </group>
      </group>
      <group position={[-13.151, 0.049, -20.081]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.216, 1.394, 1.579]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.025}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-5.167, 10.44, -2.858]} rotation={[0, 0, -Math.PI / 2]} scale={[0.963, 1, 1]}>
              <mesh geometry={nodes['woodbottom015_Material_#25_0006'].geometry} material={materials['Material_25.080']} />
              <mesh geometry={nodes['woodbottom015_Material_#25_0006_1'].geometry} material={materials['Material_25.081']} />
              <mesh geometry={nodes['woodbottom015_Material_#25_0006_2'].geometry} material={materials['Material_25.082']} />
              <mesh geometry={nodes['woodbottom015_Material_#25_0006_3'].geometry} material={materials['Material_25.083']} />
              <mesh geometry={nodes['woodbottom015_Material_#25_0006_4'].geometry} material={materials['Material_25.084']} />
              <mesh geometry={nodes['woodbottom015_Material_#25_0006_5'].geometry} material={materials['Material_25.085']} />
              <mesh geometry={nodes['woodbottom015_Material_#25_0006_6'].geometry} material={materials['Material_25.086']} />
              <mesh geometry={nodes['woodbottom015_Material_#25_0006_7'].geometry} material={materials['Material_25.087']} />
            </group>
          </group>
        </group>
      </group>
      <group position={[104.757, -0.002, 55.209]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.098, 0.1, 0.031]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-175, 600, 0]} rotation={[Math.PI / 2, 0, Math.PI]} scale={100}>
            <group position={[8.598, 8.707, 4.528]} scale={[0.651, 0.683, 1]}>
              <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0004_1.geometry} material={materials['Material.010']} />
              <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0004_2.geometry} material={materials['Material.011']} />
              <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0004_3.geometry} material={materials['Material.012']} />
              <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0004_4.geometry} material={materials['Material.013']} />
              <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0004_5.geometry} material={materials['Material.008']} />
              <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0004_6.geometry} material={materials['Material.009']} />
              <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0004_7.geometry} material={materials['Material.005']} />
              <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0004_8.geometry} material={materials['Material.006']} />
            </group>
          </group>
        </group>
      </group>
      <group position={[85.275, -0.002, 55.209]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.098, 0.1, 0.031]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-175, 600, 0]} rotation={[Math.PI / 2, 0, Math.PI]} scale={100}>
            <group position={[9.203, 8.705, 4.528]} scale={[0.651, 0.683, 1]}>
              <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_1.geometry} material={materials['Material.014']} />
              <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_2.geometry} material={materials['Material.015']} />
              <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_3.geometry} material={materials['Material.016']} />
              <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0005_4.geometry} material={materials['Material.017']} />
            </group>
          </group>
        </group>
      </group>
      <group position={[85.275, -0.002, 82.18]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.098, 0.1, 0.031]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-175, 600, 0]} rotation={[Math.PI / 2, 0, Math.PI]} scale={100}>
            <group position={[6.604, 8.705, 4.528]} scale={[0.651, 0.683, 1]}>
              <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0007.geometry} material={materials['Material.026']} />
              <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0007_1.geometry} material={materials['Material.027']} />
              <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0007_2.geometry} material={materials['Material.028']} />
              <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0007_3.geometry} material={materials['Material.029']} />
            </group>
          </group>
        </group>
      </group>
      <group position={[85.275, -0.002, 82.18]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.098, 0.1, 0.031]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-175, 600, 0]} rotation={[Math.PI / 2, 0, Math.PI]} scale={100}>
            <group position={[9.207, 8.705, 4.528]} scale={[0.651, 0.683, 1]}>
              <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0008.geometry} material={materials['Material.030']} />
              <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0008_1.geometry} material={materials['Material.031']} />
              <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0008_2.geometry} material={materials['Material.032']} />
              <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0008_3.geometry} material={materials['Material.033']} />
            </group>
          </group>
        </group>
      </group>
      <group position={[59.965, -0.002, 82.18]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.098, 0.1, 0.031]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-175, 600, 0]} rotation={[Math.PI / 2, 0, Math.PI]} scale={100}>
            <group position={[9.216, 8.705, 4.528]} scale={[0.651, 0.683, 1]}>
              <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0009.geometry} material={materials['Material.034']} />
              <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0009_1.geometry} material={materials['Material.035']} />
              <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0009_2.geometry} material={materials['Material.036']} />
              <mesh geometry={nodes.P_ceiling_2x2_2001_Material_0009_3.geometry} material={materials['Material.037']} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/backrooms_another_level.glb')
