/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 door.glb 
Author: witnessk (https://sketchfab.com/witnessk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/door-with-frame-2f2f149f3ec44d658a02c1f924dfa449
Title: Door with frame
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody, useRevoluteJoint } from "@react-three/rapier";

export function Door2() {
  const { nodes, materials }:any = useGLTF('/door.glb')
  const doorRef = useRef<any>();
  const frameRef = useRef<any>();

  const hinge = useRevoluteJoint(frameRef, doorRef, [
    // Position of the joint in bodyA's local space
    [0, 0, 0],
    // Position of the joint in bodyB's local space
    [0, 1, 0],
    // Axis of the joint, expressed in the local-space of
    // the rigid-bodies it is attached to. Cannot be [0,0,0].
    [0, 1, 0]
  ])
  

  



  return (
    <group dispose={null} position={[-3.5,3,0]}>
      <group rotation={[-Math.PI / 2, 0, 0]}  scale={1.75}>
       

       <RigidBody userData={{
        joint: hinge
       }} colliders="trimesh" ref={doorRef}>
        <group  position={[-0.435, 0.25, 0.1]}>
          <mesh geometry={nodes.Plane001_Glossy_0.geometry} material={materials.Glossy} />
          <mesh geometry={nodes.Plane001_Door_0.geometry} material={materials.Door} />
          <mesh geometry={nodes.Plane003_Door_0.geometry} material={materials.Door} position={[0.852, 0.017, 0.782]} />
          <mesh geometry={nodes.Circle002_Glossy_0.geometry} material={materials.Glossy} position={[0.81, 0.043, 0.803]} />
        </group>
        </RigidBody>


        <RigidBody ref={frameRef} type='fixed' colliders="trimesh">
        <mesh  geometry={nodes.Plane002_Door_0.geometry} material={materials.Door} />
        </RigidBody>
        

      </group>
    </group>
  )
}

useGLTF.preload('/door.glb')
