/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 gun_targets.glb 
Author: FrodoUndead (https://sketchfab.com/FrodoUndead)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gun-targets-eb9fbe283faa41ef8685359a0769d303
Title: Gun Targets
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Targets() {
  const { nodes, materials }:any = useGLTF('/gun_targets.glb')
  return (
    <group  dispose={null} position={[0,1,0]} scale={0.075}>
      <group position={[-105.543, 0, 0]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Targets} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Targets} />
      </group>
      <group position={[-75.509, 0, 0]}>
        <mesh geometry={nodes.Object_8.geometry} material={materials.Targets} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Targets} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Targets} />
      </group>
      <group position={[0.003, 28.3, -305.061]}>
        <mesh geometry={nodes.Object_14.geometry} material={materials.Targets} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Targets} />
      </group>
      <mesh geometry={nodes.Object_18.geometry} material={materials.Targets} rotation={[Math.PI, 0, 0]} scale={[-1.832, 1.832, 1.832]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.Targets} position={[-38.032, 0, 0]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.Targets} position={[-75.509, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/gun_targets.glb')
