/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 key_with_tag.glb 
Author: AxonFXDesigns (https://sketchfab.com/AxonFXDesigns)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/key-with-tag-16ea3fbecc6346df9859f0e18406951b
Title: Key with Tag
*/

import { useGLTF } from '@react-three/drei'



interface keyProps{
  showKey : Boolean
  setShowKey : any
  setHasKey : any,
}

export function Keys(props:keyProps) {
  const { nodes, materials }:any = useGLTF('/key_with_tag.glb')
  const {showKey, setShowKey, setHasKey} = props

  function handlePickUp (e:any){
    if(!showKey){
      return
    }
    if(e.code === "KeyE" && showKey){
      const pickUp = new Audio("./Sounds/key-get-39925.mp3")
      setShowKey(false)
      pickUp.play()
      setHasKey(true)
    }
    
  }
  
 window.addEventListener("keypress", handlePickUp)

  return (
    
     <group dispose={null} scale={3} position={[4.75,2.35,-6.25]}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.701}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.SM_Key_Key_0.geometry} material={materials.material} position={[0, 0.578, -2.126]} rotation={[-1.505, -0.26, 1.866]} scale={100} />
          <mesh geometry={nodes.SM_Ring_Ring_0.geometry} material={materials.Ring} position={[0, 0.559, 0]} rotation={[-Math.PI / 2, 0.227, 0]} scale={100} />
          <mesh geometry={nodes.SM_KeyTag_KeyTag_0.geometry} material={materials.KeyTag} position={[0.291, 0.546, 2.395]} rotation={[-1.661, -0.208, -1.984]} scale={100} />
        </group>
      </group>
    </group>
    
  )
}

useGLTF.preload('/key_with_tag.glb')
