/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 mannequin.glb 
Author: Veterock (https://sketchfab.com/windofglass)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mannequin-9266cb240ed343c3b69b675e1b4930c4
Title: Mannequin
*/

import {  useRef } from 'react'
import { useGLTF } from '@react-three/drei'



export function Mannequin() {
  const { nodes, materials }:any = useGLTF('/mannequin.glb')
  const headRef = useRef<any>()
 
    
  return (
    <group dispose={null} position={[-6.75,0.25,7.5]} ref={headRef} rotation={[0,2,0]} scale={2} >
       <mesh geometry={nodes.mannequin_Material_0.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/mannequin.glb')
