/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 prop_pen_and_paper.glb 
Author: Pieter (https://sketchfab.com/cartonpieter)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/prop-pen-and-paper-d14d5015fd774987a0988c973b798753
Title: PROP: pen and paper
*/

import {  useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import usePlayerControls from './inputs'
import { useFrame, useThree } from '@react-three/fiber'


interface bookProps{
  openDiary : any,
}

export function Diary3(props:bookProps) {
  const {openDiary} = props
  const [canOpen, setCanOpen] = useState<Boolean>(false)
  const { nodes, materials }:any = useGLTF('/prop_pen_and_paper.glb')
  const bookRef = useRef<any>()
  const {interact} = usePlayerControls()
  const {camera} = useThree()
  

  useFrame(()=>{
   
    const position = bookRef.current.position
    const distance = position.distanceTo(camera.position)
    if(interact && canOpen && distance < 2.8){
      bookRef.current.rotation.y = 0
      openDiary(true)
      setCanOpen(false)
    }
  })
 
  function openBook(){
     if(bookRef.current){
      setCanOpen(true)
      console.log("can interact")
  }
}

  return (
    <group position={[-4,1.6,6.3]}  dispose={null} scale={0.0004} ref={bookRef} onPointerOver={openBook}>
      <mesh  geometry={nodes.papier_Material_0.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, Math.PI]} scale={100} />
    </group>
  )
}

useGLTF.preload('/prop_pen_and_paper.glb')
