// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.2.14 subway.glb 
// Author: Qifan Zhang (https://sketchfab.com/qifanzhang)
// License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
// Source: https://sketchfab.com/3d-models/2-floor-dirty-new-york-subway-station-e72b88b8177f47769b37b2787bd97300
// Title: 2-Floor Dirty New York Subway Station
// */

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Subway() {
  const { nodes, materials }:any = useGLTF('/subway.glb')
  return (
    <group  dispose={null}>
      <group scale={0.01}>
        <group position={[3157.564, 2313.401, 3697.454]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.393}>
          <mesh geometry={nodes.pCube70_M_Turnstile_0.geometry} material={materials.M_Turnstile} position={[924.467, -105.112, 0]} rotation={[Math.PI, 0, -Math.PI]} scale={0.718} />
          <mesh geometry={nodes.pCube71_M_Turnstile_0.geometry} material={materials.M_Turnstile} position={[331.614, -71.786, -113.527]} rotation={[Math.PI, 0, -2.88]} scale={[0.338, 0.028, 1.29]} />
          <mesh geometry={nodes.pCube72_M_Turnstile_0.geometry} material={materials.M_Turnstile} position={[-285.591, -71.786, -113.527]} rotation={[Math.PI, 0, -2.88]} scale={[0.338, 0.028, 1.29]} />
          <mesh geometry={nodes.pCube73_M_Turnstile_0.geometry} material={materials.M_Turnstile} position={[-894.498, -71.786, -113.527]} rotation={[Math.PI, 0, -2.88]} scale={[0.338, 0.028, 1.29]} />
          <mesh geometry={nodes.polySurface1_M_Turnstile_0.geometry} material={materials.M_Turnstile} position={[577.636, -0.001, 0]} rotation={[Math.PI, 0, -Math.PI]} scale={0.718} />
          <mesh geometry={nodes.polySurface2_M_Turnstile_0.geometry} material={materials.M_Turnstile} position={[-33.5, -0.001, 0]} rotation={[Math.PI, 0, -Math.PI]} scale={0.718} />
          <mesh geometry={nodes.polySurface3_M_Turnstile_0.geometry} material={materials.M_Turnstile} position={[-642.968, -0.001, 0]} rotation={[Math.PI, 0, -Math.PI]} scale={0.718} />
        </group>
        <group position={[-2058.097, -1750.447, -7293.624]}>
          <mesh geometry={nodes.Bench_M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[615, 239, -2836]} />
          <mesh geometry={nodes.Cone_M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[-1179, 3272, 14584]} rotation={[0, 0.378, 0]} scale={1.124} />
          <mesh geometry={nodes.Cone3_M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[-873, 3272, 14919]} rotation={[0, -0.238, 0]} scale={1.124} />
          <mesh geometry={nodes.RoadBlock_M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[-980.741, 3343.52, 15266.628]} scale={1.124} />
          <mesh geometry={nodes.Trashcan_M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[618, 341.55, -4691]} rotation={[0, -1.083, 0]} scale={[1.812, 2.95, 1.812]} />
          <mesh geometry={nodes.Wet_Sign_M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[1479, 195.152, 8156]} />
          <mesh geometry={nodes.Bench__1__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[615, 239, -776]} />
          <mesh geometry={nodes.Bench__2__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[615, 239, -8665]} />
          <mesh geometry={nodes.Bench__3__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[615, 239, -6605]} />
          <mesh geometry={nodes.Bench__4__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[615, 239, 14039.999]} />
          <mesh geometry={nodes.Bench__5__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[615, 239, 16766]} />
          <mesh geometry={nodes.Trashcan__1__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[643, 321, 15369]} rotation={[0, -1.465, 0]} scale={[1.812, 2.95, 1.812]} />
          <mesh geometry={nodes.Trashcan__2__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[2357, 3430, 13153]} rotation={[0, -1.226, 0]} scale={[1.812, 2.95, 1.812]} />
          <mesh geometry={nodes.Trashcan__3__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[5389, 3430, 7239]} rotation={[0, 0.894, 0]} scale={[1.812, 2.95, 1.812]} />
          <mesh geometry={nodes.Pipes_1_M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[2241, 2597, -9931]} scale={1.203} />
          <mesh geometry={nodes.Pipes__1__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[2241, 2597, -9023.999]} scale={1.203} />
          <mesh geometry={nodes.Pipes__2__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[2241, 2597, -8140.001]} scale={1.203} />
          <mesh geometry={nodes.Pipes__3__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[2241, 2597, -7233]} scale={1.203} />
          <mesh geometry={nodes.Pipes__4__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[2241, 2597, -6325]} scale={1.203} />
          <mesh geometry={nodes.Pipes__5__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[2241, 2597, -5418]} scale={1.203} />
          <mesh geometry={nodes.Pipes__6__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[2241, 2597, -4534.001]} scale={1.203} />
          <mesh geometry={nodes.Pipes__7__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[2241, 2597, -3627.001]} scale={1.203} />
          <mesh geometry={nodes.Pipes__8__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[2241, 2597, -2774]} scale={1.203} />
          <mesh geometry={nodes.Pipes__9__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[2241, 2597, -1866.999]} scale={1.203} />
          <mesh geometry={nodes.Pipes__10__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[2241, 2597, -983]} scale={1.203} />
          <mesh geometry={nodes.Pipes__11__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[2241, 2597, -75.999]} scale={1.203} />
          <mesh geometry={nodes.Pipes__12__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[2241, 2597, 832.001]} scale={1.203} />
          <mesh geometry={nodes.Pipes__13__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[2241, 2597, 1739.001]} scale={1.203} />
          <mesh geometry={nodes.Pipes__14__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[2241, 2597, 2623]} scale={1.203} />
          <mesh geometry={nodes.Pipes__15__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[2241, 2597, 3530]} scale={1.203} />
          <mesh geometry={nodes.Pipes__16__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[2241, 2597, 4423]} scale={1.203} />
          <mesh geometry={nodes.Pipes__17__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[2241, 2597, 5330]} scale={1.203} />
          <mesh geometry={nodes.Pipes__18__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[2241, 2597, 6213.999]} scale={1.203} />
          <mesh geometry={nodes.Pipes__19__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[2241, 2597, 7120.999]} scale={1.203} />
          <mesh geometry={nodes.Pipes__20__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[2241, 2597, 8029]} scale={1.203} />
          <mesh geometry={nodes.Pipes__21__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[2241, 2597, 8936]} scale={1.203} />
          <mesh geometry={nodes.Pipes__22__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[2241, 2597, 9819.998]} scale={1.203} />
          <mesh geometry={nodes.Pipes__23__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[2241, 2597, 10726.999]} scale={1.203} />
          <mesh geometry={nodes.Pipes__24__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[2241, 2597, 11580]} scale={1.203} />
          <mesh geometry={nodes.Pipes__25__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[2241, 2597, 12487.001]} scale={1.203} />
          <mesh geometry={nodes.Pipes__26__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[2241, 2597, 13370.999]} scale={1.203} />
          <mesh geometry={nodes.Pipes__27__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[2241, 2597, 14278]} scale={1.203} />
          <mesh geometry={nodes.Pipes__28__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[2241, 2597, 15185.998]} scale={1.203} />
          <mesh geometry={nodes.Pipes__29__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[2241, 2597, 16092.999]} scale={1.203} />
          <mesh geometry={nodes.Pipes__30__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[2241, 2597, 16976.998]} scale={1.203} />
          <mesh geometry={nodes.Pipes__31__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[2241, 2597, 17884]} scale={1.203} />
          <mesh geometry={nodes.Pipes__32__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[2241, 2597, 18764]} scale={1.203} />
          <mesh geometry={nodes.Wet_Sign__1__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[2610, 3292.6, 6060]} />
          <mesh geometry={nodes.Wet_Sign__2__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[8650, 3292.6, 5860]} rotation={[0, -0.677, 0]} />
          <mesh geometry={nodes.Wet_Sign__3__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[7840, 3292.6, 8910]} rotation={[0, -0.438, 0]} />
          <mesh geometry={nodes.Cone__1__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[-771, 3272, 15669]} rotation={[0, 0.378, 0]} scale={1.124} />
          <mesh geometry={nodes.Cone__2__M_SubwayAssets_0.geometry} material={materials.M_SubwayAssets} position={[-480, 3272, 15762]} rotation={[-Math.PI, -1.068, -Math.PI]} scale={1.124} />
        </group>
        <group position={[-921.436, -1769.599, -2953.546]}>
          <group position={[3650, 2910, 6630]}>
            <group position={[0, 193, 0]}>
              <group position={[-239.669, 1360, 496.593]}>
                <group position={[0, -150, 0]} scale={[1, 0.875, 1]}>
                  <group position={[2825.174, -40.214, -821.655]} rotation={[0, 0, 0.721]} scale={[0.393, 8.718, 0.314]}>
                    <mesh geometry={nodes.polySurface79_M_Addition_0.geometry} material={materials.M_Addition} />
                    <mesh geometry={nodes.polySurface80_M_Addition_0.geometry} material={materials.M_Addition} position={[732.364, -10.192, 0]} />
                    <mesh geometry={nodes.polySurface84_M_Addition_0.geometry} material={materials.M_Addition} position={[3031.501, -120.055, 0]} />
                    <mesh geometry={nodes.polySurface85_M_Addition_0.geometry} material={materials.M_Addition} position={[3763.866, -130.247, 0]} />
                    <mesh geometry={nodes.polySurface88_M_Addition_0.geometry} material={materials.M_Addition} position={[-14204.965, 562.552, 0]} />
                    <mesh geometry={nodes.polySurface89_M_Addition_0.geometry} material={materials.M_Addition} position={[-13472.602, 552.36, 0]} />
                    <mesh geometry={nodes.polySurface91_M_Addition_0.geometry} material={materials.M_Addition} position={[-10441.1, 432.305, 0]} />
                    <mesh geometry={nodes.polySurface94_M_Addition_0.geometry} material={materials.M_Addition} position={[-11173.464, 442.497, 0]} />
                    <mesh geometry={nodes.polySurface135_M_Addition_0.geometry} material={materials.M_Addition} position={[-10441.1, 432.305, 0]} />
                    <mesh geometry={nodes.polySurface138_M_Addition_0.geometry} material={materials.M_Addition} position={[732.364, -10.192, 0]} />
                    <mesh geometry={nodes.polySurface139_M_Addition_0.geometry} material={materials.M_Addition} />
                    <mesh geometry={nodes.polySurface144_M_Addition_0.geometry} material={materials.M_Addition} position={[-11173.464, 442.497, 0]} />
                    <mesh geometry={nodes.polySurface147_M_Addition_0.geometry} material={materials.M_Addition} position={[3763.866, -130.247, 0]} />
                    <mesh geometry={nodes.polySurface151_M_Addition_0.geometry} material={materials.M_Addition} position={[-13472.602, 552.36, 0]} />
                    <mesh geometry={nodes.polySurface153_M_Addition_0.geometry} material={materials.M_Addition} position={[3031.501, -120.055, 0]} />
                    <mesh geometry={nodes.polySurface156_M_Addition_0.geometry} material={materials.M_Addition} position={[-14204.965, 562.552, 0]} />
                  </group>
                  <group position={[2683.031, -181.439, -821.655]} rotation={[0, 0, 0.721]} scale={[0.393, 8.718, 0.314]}>
                    <mesh geometry={nodes.polySurface81_M_Addition_0.geometry} material={materials.M_Addition} />
                    <mesh geometry={nodes.polySurface82_M_Addition_0.geometry} material={materials.M_Addition} position={[1276.048, -31.723, 0]} />
                    <mesh geometry={nodes.polySurface83_M_Addition_0.geometry} material={materials.M_Addition} position={[3031.501, -120.055, 0]} />
                    <mesh geometry={nodes.polySurface86_M_Addition_0.geometry} material={materials.M_Addition} position={[4307.55, -151.779, 0]} />
                    <mesh geometry={nodes.polySurface87_M_Addition_0.geometry} material={materials.M_Addition} position={[-14204.965, 562.552, 0]} />
                    <mesh geometry={nodes.polySurface90_M_Addition_0.geometry} material={materials.M_Addition} position={[-12928.915, 530.828, 0]} />
                    <mesh geometry={nodes.polySurface92_M_Addition_0.geometry} material={materials.M_Addition} position={[-9897.415, 410.773, 0]} />
                    <mesh geometry={nodes.polySurface93_M_Addition_0.geometry} material={materials.M_Addition} position={[-11173.464, 442.497, 0]} />
                    <mesh geometry={nodes.polySurface125_M_Addition_0.geometry} material={materials.M_Addition} position={[1276.048, -31.723, 0]} />
                    <mesh geometry={nodes.polySurface127_M_Addition_0.geometry} material={materials.M_Addition} position={[3031.501, -120.055, 0]} />
                    <mesh geometry={nodes.polySurface132_M_Addition_0.geometry} material={materials.M_Addition} position={[-12928.915, 530.828, 0]} />
                    <mesh geometry={nodes.polySurface133_M_Addition_0.geometry} material={materials.M_Addition} position={[-11173.464, 442.497, 0]} />
                    <mesh geometry={nodes.polySurface137_M_Addition_0.geometry} material={materials.M_Addition} position={[4307.55, -151.779, 0]} />
                    <mesh geometry={nodes.polySurface145_M_Addition_0.geometry} material={materials.M_Addition} />
                    <mesh geometry={nodes.polySurface150_M_Addition_0.geometry} material={materials.M_Addition} position={[-9897.415, 410.773, 0]} />
                    <mesh geometry={nodes.polySurface154_M_Addition_0.geometry} material={materials.M_Addition} position={[-14204.965, 562.552, 0]} />
                  </group>
                  <group position={[-1375.595, -49.664, -2544.676]}>
                    <mesh geometry={nodes.polySurface98_M_Addition_0.geometry} material={materials.M_Addition} position={[-2034.735, -4044.107, -4581.918]} />
                    <mesh geometry={nodes.polySurface109_M_Addition_0.geometry} material={materials.M_Addition} position={[-2034.735, -4044.107, -4581.918]} />
                    <mesh geometry={nodes.polySurface110_M_Addition_0.geometry} material={materials.M_Addition} position={[-2034.735, -4044.107, -4581.918]} />
                    <mesh geometry={nodes.polySurface111_M_Addition_0.geometry} material={materials.M_Addition} position={[-2034.735, -4044.107, -4581.918]} />
                    <mesh geometry={nodes.polySurface112_M_Addition_0.geometry} material={materials.M_Addition} position={[-2034.735, -4044.107, -4581.918]} />
                    <mesh geometry={nodes.polySurface113_M_Addition_0.geometry} material={materials.M_Addition} position={[-2034.735, -4044.107, -4581.918]} />
                    <mesh geometry={nodes.polySurface115_M_Addition_0.geometry} material={materials.M_Addition} position={[-2034.735, -4044.107, -4581.918]} />
                    <mesh geometry={nodes.polySurface116_M_Addition_0.geometry} material={materials.M_Addition} position={[-2034.735, -4044.107, -4581.918]} />
                    <mesh geometry={nodes.polySurface117_M_Addition_0.geometry} material={materials.M_Addition} position={[-2034.735, -4044.107, -4581.918]} />
                    <mesh geometry={nodes.polySurface118_M_Addition_0.geometry} material={materials.M_Addition} position={[-2034.735, -4044.107, -4581.918]} />
                    <mesh geometry={nodes.polySurface119_M_Addition_0.geometry} material={materials.M_Addition} position={[-2034.735, -4044.107, -4581.918]} />
                    <mesh geometry={nodes.polySurface120_M_Addition_0.geometry} material={materials.M_Addition} position={[-2034.735, -4044.107, -4581.918]} />
                    <mesh geometry={nodes.polySurface121_M_Addition_0.geometry} material={materials.M_Addition} position={[-2034.735, -4044.107, -4581.918]} />
                    <mesh geometry={nodes.polySurface122_M_Addition_0.geometry} material={materials.M_Addition} position={[-2034.735, -4044.107, -4581.918]} />
                    <mesh geometry={nodes.polySurface124_M_Addition_0.geometry} material={materials.M_Addition} position={[-87.834, -321.083, 1684.216]} scale={[1, 3.17, 1]} />
                    <mesh geometry={nodes.polySurface126_M_Addition_0.geometry} material={materials.M_Addition} position={[-2034.735, -4044.107, -4581.918]} />
                    <mesh geometry={nodes.polySurface128_M_Addition_0.geometry} material={materials.M_Addition} position={[-87.834, 295, 1684.216]} scale={[1, 1.12, 1]} />
                    <mesh geometry={nodes.polySurface129_M_Addition_0.geometry} material={materials.M_Addition} position={[-2034.735, -4044.107, -4581.918]} />
                    <mesh geometry={nodes.polySurface130_M_Addition_0.geometry} material={materials.M_Addition} position={[-2034.735, -4044.107, -4581.918]} />
                    <mesh geometry={nodes.polySurface131_M_Addition_0.geometry} material={materials.M_Addition} position={[-2034.735, -4044.107, -4581.918]} />
                    <mesh geometry={nodes.polySurface134_M_Addition_0.geometry} material={materials.M_Addition} position={[-2034.735, -4044.107, -4581.918]} />
                    <mesh geometry={nodes.polySurface136_M_Addition_0.geometry} material={materials.M_Addition} position={[-2034.735, -4044.107, -4581.918]} />
                    <mesh geometry={nodes.polySurface140_M_Addition_0.geometry} material={materials.M_Addition} position={[-2034.735, -4044.107, -4581.918]} />
                    <mesh geometry={nodes.polySurface141_M_Addition_0.geometry} material={materials.M_Addition} position={[-2034.735, -4044.107, -4581.918]} />
                    <mesh geometry={nodes.polySurface143_M_Addition_0.geometry} material={materials.M_Addition} position={[-2034.735, -4044.107, -4581.918]} />
                    <mesh geometry={nodes.polySurface146_M_Addition_0.geometry} material={materials.M_Addition} position={[-2034.735, -4044.107, -4581.918]} />
                    <mesh geometry={nodes.polySurface148_M_Addition_0.geometry} material={materials.M_Addition} position={[-2034.735, -4044.107, -4581.918]} />
                    <mesh geometry={nodes.polySurface149_M_Addition_0.geometry} material={materials.M_Addition} position={[-2034.735, -4044.107, -4581.918]} />
                  </group>
                  <mesh geometry={nodes.pCube94_M_Addition_0.geometry} material={materials.M_Addition} position={[2655.275, -1129.656, -821.655]} scale={[0.459, 28.575, 0.314]} />
                  <mesh geometry={nodes.pCube95_M_Addition_0.geometry} material={materials.M_Addition} position={[3183.274, -1129.656, -821.655]} scale={[0.459, 28.575, 0.314]} />
                  <mesh geometry={nodes.pCube96_M_Addition_0.geometry} material={materials.M_Addition} position={[4592.409, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube97_M_Addition_0.geometry} material={materials.M_Addition} position={[4416.409, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube98_M_Addition_0.geometry} material={materials.M_Addition} position={[4418.487, -167.446, -821.655]} rotation={[0, 0, Math.PI / 2]} scale={[0.481, 16.229, 0.421]} />
                  <mesh geometry={nodes.pCube99_M_Addition_0.geometry} material={materials.M_Addition} position={[5120.409, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube100_M_Addition_0.geometry} material={materials.M_Addition} position={[4418.487, 184.157, -821.655]} rotation={[0, 0, Math.PI / 2]} scale={[0.481, 16.229, 0.421]} />
                  <mesh geometry={nodes.pCube101_M_Addition_0.geometry} material={materials.M_Addition} position={[3888.41, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube102_M_Addition_0.geometry} material={materials.M_Addition} position={[4064.409, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube103_M_Addition_0.geometry} material={materials.M_Addition} position={[4240.41, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube104_M_Addition_0.geometry} material={materials.M_Addition} position={[4768.409, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube105_M_Addition_0.geometry} material={materials.M_Addition} position={[4944.409, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube106_M_Addition_0.geometry} material={materials.M_Addition} position={[4240.41, -1129.656, -821.655]} scale={[0.459, 28.575, 0.314]} />
                  <mesh geometry={nodes.pCube107_M_Addition_0.geometry} material={materials.M_Addition} position={[4768.409, -1129.656, -821.655]} scale={[0.459, 28.575, 0.314]} />
                  <mesh geometry={nodes.pCube108_M_Addition_0.geometry} material={materials.M_Addition} position={[5293.984, 30.668, -821.655]} scale={[0.655, 28.115, 0.658]} />
                  <mesh geometry={nodes.pCube109_M_Addition_0.geometry} material={materials.M_Addition} position={[-4420.325, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube110_M_Addition_0.geometry} material={materials.M_Addition} position={[-4596.325, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube111_M_Addition_0.geometry} material={materials.M_Addition} position={[-4594.246, -167.446, -821.655]} rotation={[0, 0, Math.PI / 2]} scale={[0.481, 16.229, 0.421]} />
                  <mesh geometry={nodes.pCube112_M_Addition_0.geometry} material={materials.M_Addition} position={[-5303.747, 30.668, -821.655]} scale={[0.655, 28.115, 0.658]} />
                  <mesh geometry={nodes.pCube113_M_Addition_0.geometry} material={materials.M_Addition} position={[-3726.943, 30.668, -821.655]} scale={[0.655, 28.115, 0.658]} />
                  <mesh geometry={nodes.pCube114_M_Addition_0.geometry} material={materials.M_Addition} position={[-3877.533, -1094.56, -821.655]} rotation={[0, 0, Math.PI / 2]} scale={[1.201, 42.095, 0.421]} />
                  <mesh geometry={nodes.pCube115_M_Addition_0.geometry} material={materials.M_Addition} position={[-3877.533, 755.82, -821.655]} rotation={[0, 0, Math.PI / 2]} scale={[0.481, 42.095, 0.421]} />
                  <mesh geometry={nodes.pCube116_M_Addition_0.geometry} material={materials.M_Addition} position={[-3892.325, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube117_M_Addition_0.geometry} material={materials.M_Addition} position={[-4594.246, 184.157, -821.655]} rotation={[0, 0, Math.PI / 2]} scale={[0.481, 16.229, 0.421]} />
                  <mesh geometry={nodes.pCube118_M_Addition_0.geometry} material={materials.M_Addition} position={[-5124.324, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube119_M_Addition_0.geometry} material={materials.M_Addition} position={[-4948.324, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube120_M_Addition_0.geometry} material={materials.M_Addition} position={[-4772.324, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube121_M_Addition_0.geometry} material={materials.M_Addition} position={[-4244.325, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube122_M_Addition_0.geometry} material={materials.M_Addition} position={[-4068.325, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube123_M_Addition_0.geometry} material={materials.M_Addition} position={[-2659.19, -1129.656, -821.655]} scale={[0.459, 28.575, 0.314]} />
                  <mesh geometry={nodes.pCube124_M_Addition_0.geometry} material={materials.M_Addition} position={[-3009.112, -167.446, -821.655]} rotation={[0, 0, Math.PI / 2]} scale={[0.481, 16.229, 0.421]} />
                  <mesh geometry={nodes.pCube125_M_Addition_0.geometry} material={materials.M_Addition} position={[-2835.19, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube126_M_Addition_0.geometry} material={materials.M_Addition} position={[-2307.19, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube127_M_Addition_0.geometry} material={materials.M_Addition} position={[-3187.19, -1129.656, -821.655]} scale={[0.459, 28.575, 0.314]} />
                  <mesh geometry={nodes.pCube128_M_Addition_0.geometry} material={materials.M_Addition} position={[-2483.19, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube129_M_Addition_0.geometry} material={materials.M_Addition} position={[-3363.19, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube130_M_Addition_0.geometry} material={materials.M_Addition} position={[-2659.19, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube131_M_Addition_0.geometry} material={materials.M_Addition} position={[-3009.112, 184.157, -821.655]} rotation={[0, 0, Math.PI / 2]} scale={[0.481, 16.229, 0.421]} />
                  <mesh geometry={nodes.pCube132_M_Addition_0.geometry} material={materials.M_Addition} position={[-3539.19, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube133_M_Addition_0.geometry} material={materials.M_Addition} position={[-3011.19, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube134_M_Addition_0.geometry} material={materials.M_Addition} position={[-3187.19, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube136_M_Addition_0.geometry} material={materials.M_Addition} position={[-4772.324, -1129.656, -821.655]} scale={[0.459, 28.575, 0.314]} />
                  <mesh geometry={nodes.pCube137_M_Addition_0.geometry} material={materials.M_Addition} position={[-4244.325, -1129.656, -821.655]} scale={[0.459, 28.575, 0.314]} />
                  <mesh geometry={nodes.pCube140_M_Addition_0.geometry} material={materials.M_Addition} position={[-1530.182, -1094.56, -821.655]} rotation={[0, 0, Math.PI / 2]} scale={[1.201, 16.759, 0.421]} />
                  <mesh geometry={nodes.pCube141_M_Addition_0.geometry} material={materials.M_Addition} position={[-2071.691, -5.697, -821.655]} scale={[0.459, 23.644, 0.314]} />
                  <mesh geometry={nodes.pCube142_M_Addition_0.geometry} material={materials.M_Addition} position={[-848.406, -5.697, -821.655]} scale={[0.459, 23.644, 0.314]} />
                  <mesh geometry={nodes.pCube155_M_Addition_0.geometry} material={materials.M_Addition} position={[-1530.182, -1094.56, -821.655]} rotation={[0, 0, Math.PI / 2]} scale={[1.201, 16.759, 0.421]} />
                  <mesh geometry={nodes.pCube156_M_Addition_0.geometry} material={materials.M_Addition} position={[5293.984, 30.668, -821.655]} scale={[0.655, 28.115, 0.658]} />
                  <mesh geometry={nodes.pCube157_M_Addition_0.geometry} material={materials.M_Addition} position={[3183.274, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube158_M_Addition_0.geometry} material={materials.M_Addition} position={[3700.656, 30.668, -821.655]} scale={[0.655, 28.115, 0.658]} />
                  <mesh geometry={nodes.pCube159_M_Addition_0.geometry} material={materials.M_Addition} position={[-4244.325, -1129.656, -821.655]} scale={[0.459, 28.575, 0.314]} />
                  <mesh geometry={nodes.pCube160_M_Addition_0.geometry} material={materials.M_Addition} position={[3183.274, -1129.656, -821.655]} scale={[0.459, 28.575, 0.314]} />
                  <mesh geometry={nodes.pCube161_M_Addition_0.geometry} material={materials.M_Addition} position={[4418.487, 184.157, -821.655]} rotation={[0, 0, Math.PI / 2]} scale={[0.481, 16.229, 0.421]} />
                  <mesh geometry={nodes.pCube162_M_Addition_0.geometry} material={materials.M_Addition} position={[-3726.943, 30.668, -821.655]} scale={[0.655, 28.115, 0.658]} />
                  <mesh geometry={nodes.pCube163_M_Addition_0.geometry} material={materials.M_Addition} position={[-2659.19, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube164_M_Addition_0.geometry} material={materials.M_Addition} position={[3359.275, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube165_M_Addition_0.geometry} material={materials.M_Addition} position={[-4244.325, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube166_M_Addition_0.geometry} material={materials.M_Addition} position={[-3011.19, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube167_M_Addition_0.geometry} material={materials.M_Addition} position={[3007.275, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube168_M_Addition_0.geometry} material={materials.M_Addition} position={[4240.41, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube169_M_Addition_0.geometry} material={materials.M_Addition} position={[-4772.324, -1129.656, -821.655]} scale={[0.459, 28.575, 0.314]} />
                  <mesh geometry={nodes.pCube170_M_Addition_0.geometry} material={materials.M_Addition} position={[-4068.325, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube172_M_Addition_0.geometry} material={materials.M_Addition} position={[5120.409, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube173_M_Addition_0.geometry} material={materials.M_Addition} position={[4240.41, -1129.656, -821.655]} scale={[0.459, 28.575, 0.314]} />
                  <mesh geometry={nodes.pCube174_M_Addition_0.geometry} material={materials.M_Addition} position={[3566.09, -1094.56, -821.655]} rotation={[0, 0, Math.PI / 2]} scale={[1.201, 43.057, 0.421]} />
                  <mesh geometry={nodes.pCube175_M_Addition_0.geometry} material={materials.M_Addition} position={[-2659.19, -1129.656, -821.655]} scale={[0.459, 28.575, 0.314]} />
                  <mesh geometry={nodes.pCube176_M_Addition_0.geometry} material={materials.M_Addition} position={[-2071.691, -5.697, -821.655]} scale={[0.459, 23.644, 0.314]} />
                  <mesh geometry={nodes.pCube177_M_Addition_0.geometry} material={materials.M_Addition} position={[3888.41, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube178_M_Addition_0.geometry} material={materials.M_Addition} position={[-4948.324, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube179_M_Addition_0.geometry} material={materials.M_Addition} position={[-3892.325, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube180_M_Addition_0.geometry} material={materials.M_Addition} position={[-4594.246, -167.446, -821.655]} rotation={[0, 0, Math.PI / 2]} scale={[0.481, 16.229, 0.421]} />
                  <mesh geometry={nodes.pCube181_M_Addition_0.geometry} material={materials.M_Addition} position={[4418.487, -167.446, -821.655]} rotation={[0, 0, Math.PI / 2]} scale={[0.481, 16.229, 0.421]} />
                  <mesh geometry={nodes.pCube182_M_Addition_0.geometry} material={materials.M_Addition} position={[-779.363, 30.668, -821.655]} scale={[0.655, 28.115, 0.658]} />
                  <mesh geometry={nodes.pCube183_M_Addition_0.geometry} material={materials.M_Addition} position={[-4772.324, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube184_M_Addition_0.geometry} material={materials.M_Addition} position={[2479.275, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube185_M_Addition_0.geometry} material={materials.M_Addition} position={[2655.275, -1129.656, -821.655]} scale={[0.459, 28.575, 0.314]} />
                  <mesh geometry={nodes.pCube186_M_Addition_0.geometry} material={materials.M_Addition} position={[-3009.112, 184.157, -821.655]} rotation={[0, 0, Math.PI / 2]} scale={[0.481, 16.229, 0.421]} />
                  <mesh geometry={nodes.pCube187_M_Addition_0.geometry} material={materials.M_Addition} position={[4768.409, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube188_M_Addition_0.geometry} material={materials.M_Addition} position={[-2483.19, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube189_M_Addition_0.geometry} material={materials.M_Addition} position={[4944.409, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube190_M_Addition_0.geometry} material={materials.M_Addition} position={[-2835.19, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube191_M_Addition_0.geometry} material={materials.M_Addition} position={[2123.853, 30.668, -821.655]} scale={[0.655, 28.115, 0.658]} />
                  <mesh geometry={nodes.pCube192_M_Addition_0.geometry} material={materials.M_Addition} position={[2831.275, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube193_M_Addition_0.geometry} material={materials.M_Addition} position={[3535.274, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube194_M_Addition_0.geometry} material={materials.M_Addition} position={[-4420.325, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube195_M_Addition_0.geometry} material={materials.M_Addition} position={[-3877.533, -1094.56, -821.655]} rotation={[0, 0, Math.PI / 2]} scale={[1.201, 42.095, 0.421]} />
                  <mesh geometry={nodes.pCube196_M_Addition_0.geometry} material={materials.M_Addition} position={[2655.275, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube197_M_Addition_0.geometry} material={materials.M_Addition} position={[-5303.747, 30.668, -821.655]} scale={[0.655, 28.115, 0.658]} />
                  <mesh geometry={nodes.pCube198_M_Addition_0.geometry} material={materials.M_Addition} position={[-3363.19, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube199_M_Addition_0.geometry} material={materials.M_Addition} position={[4416.409, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube200_M_Addition_0.geometry} material={materials.M_Addition} position={[-2133.615, 30.668, -821.655]} scale={[0.655, 28.115, 0.658]} />
                  <mesh geometry={nodes.pCube201_M_Addition_0.geometry} material={materials.M_Addition} position={[4768.409, -1129.656, -821.655]} scale={[0.459, 28.575, 0.314]} />
                  <mesh geometry={nodes.pCube202_M_Addition_0.geometry} material={materials.M_Addition} position={[4592.409, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube203_M_Addition_0.geometry} material={materials.M_Addition} position={[-3877.533, 755.82, -821.655]} rotation={[0, 0, Math.PI / 2]} scale={[0.481, 42.095, 0.421]} />
                  <mesh geometry={nodes.pCube204_M_Addition_0.geometry} material={materials.M_Addition} position={[4064.409, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube205_M_Addition_0.geometry} material={materials.M_Addition} position={[-2307.19, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube206_M_Addition_0.geometry} material={materials.M_Addition} position={[3566.09, 755.82, -821.655]} rotation={[0, 0, Math.PI / 2]} scale={[0.481, 43.057, 0.421]} />
                  <mesh geometry={nodes.pCube207_M_Addition_0.geometry} material={materials.M_Addition} position={[2833.353, 184.157, -821.655]} rotation={[0, 0, Math.PI / 2]} scale={[0.481, 16.229, 0.421]} />
                  <mesh geometry={nodes.pCube208_M_Addition_0.geometry} material={materials.M_Addition} position={[-3187.19, -1129.656, -821.655]} scale={[0.459, 28.575, 0.314]} />
                  <mesh geometry={nodes.pCube209_M_Addition_0.geometry} material={materials.M_Addition} position={[-5124.324, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube210_M_Addition_0.geometry} material={materials.M_Addition} position={[-4596.325, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube211_M_Addition_0.geometry} material={materials.M_Addition} position={[-3009.112, -167.446, -821.655]} rotation={[0, 0, Math.PI / 2]} scale={[0.481, 16.229, 0.421]} />
                  <mesh geometry={nodes.pCube212_M_Addition_0.geometry} material={materials.M_Addition} position={[-3539.19, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube213_M_Addition_0.geometry} material={materials.M_Addition} position={[2833.353, -167.446, -821.655]} rotation={[0, 0, Math.PI / 2]} scale={[0.481, 16.229, 0.421]} />
                  <mesh geometry={nodes.pCube214_M_Addition_0.geometry} material={materials.M_Addition} position={[-848.406, -5.697, -821.655]} scale={[0.459, 23.644, 0.314]} />
                  <mesh geometry={nodes.pCube215_M_Addition_0.geometry} material={materials.M_Addition} position={[-3187.19, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                  <mesh geometry={nodes.pCube216_M_Addition_0.geometry} material={materials.M_Addition} position={[-4594.246, 184.157, -821.655]} rotation={[0, 0, Math.PI / 2]} scale={[0.481, 16.229, 0.421]} />
                  <mesh geometry={nodes.pCube217_M_Addition_0.geometry} material={materials.M_Addition} position={[2303.275, 98.407, -821.655]} scale={[0.459, 26.25, 0.314]} />
                </group>
              </group>
              <group position={[5340.388, 39.914, 4232.242]} rotation={[0, -Math.PI / 2, 0]} scale={0.069}>
                <mesh geometry={nodes.polySurface53_M_Stairs_0.geometry} material={materials.M_Stairs} position={[0, 13700, -11470]} rotation={[-Math.PI, 0, -Math.PI]} scale={[18.649, 14.485, 14.485]} />
                <mesh geometry={nodes.polySurface57_M_Stairs_0.geometry} material={materials.M_Stairs} position={[-0.002, 34835.063, -32881.047]} rotation={[-Math.PI, 0, -Math.PI]} scale={14.485} />
                <mesh geometry={nodes.polySurface78_M_Stairs_0.geometry} material={materials.M_Stairs} position={[-0.002, 33835.066, -31195.762]} rotation={[-Math.PI, 0, -Math.PI]} scale={14.485} />
              </group>
              <mesh geometry={nodes.pillar1_M_Stairs_0.geometry} material={materials.M_Stairs} position={[-1460.922, 1271.988, -3640.861]} scale={[3.359, 28.115, 5.031]} />
              <mesh geometry={nodes.pillar2_M_Stairs_0.geometry} material={materials.M_Stairs} position={[2645.861, 1271.988, -3640.861]} scale={[3.359, 28.115, 5.031]} />
              <mesh geometry={nodes.pillar3_M_Stairs_0.geometry} material={materials.M_Stairs} position={[2645.861, 1271.988, 2144.304]} scale={[3.359, 28.115, 5.455]} />
              <mesh geometry={nodes.pillar4_M_Stairs_0.geometry} material={materials.M_Stairs} position={[-1460.922, 1271.988, 2144.304]} scale={[3.359, 28.115, 5.455]} />
            </group>
            <group position={[-1114.532, 2744, -1241.44]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[140.231, 145.357, 3.766]}>
              <mesh geometry={nodes.up_ceiling_M_Structure_0.geometry} material={materials.M_Structure} />
              <mesh geometry={nodes.stiar_sign_M_Stairs_0.geometry} material={materials.M_Stairs} position={[9.996, -23.414, 124.032]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.006, 0.223, 0.006]} />
              <mesh geometry={nodes.sign_M_Stairs_0.geometry} material={materials.M_Stairs} position={[-10.44, 15.602, 124.032]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[0.006, 0.223, 0.006]} />
            </group>
            <group position={[309.005, 2090, -6223.287]} scale={[148.519, 38.018, 4.036]}>
              <group position={[-7.173, -18.708, 53.033]} rotation={[0, Math.PI / 2, 0]} scale={[0.248, 0.026, 0.007]}>
                <mesh geometry={nodes.TheEndlessSummer_M_Posters_0.geometry} material={materials.M_Posters} position={[-17.344, 0, -1117.115]} scale={[0.435, 16.24, 19.998]} />
                <mesh geometry={nodes.Triangle_M_Posters_0.geometry} material={materials.M_Posters} position={[-17.344, 0, 1015.594]} scale={[0.435, 16.24, 19.998]} />
              </group>
              <group position={[-2.081, -50.817, 1541.93]} scale={[0.007, 0.026, 0.248]}>
                <group position={[3406.3, 739.475, -6002.059]}>
                  <mesh geometry={nodes.door_M_Structure_0.geometry} material={materials.M_Structure} />
                  <mesh geometry={nodes.Plane_Employee_0.geometry} material={materials.Employee} position={[-278, 359.6, 25.476]} rotation={[Math.PI / 2, 0, 0.027]} scale={[0.33, 0.146, 0.139]} />
                </group>
                <group position={[3729.904, 739.475, -6021.718]} rotation={[0, -0.07, 0]}>
                  <mesh geometry={nodes.door1_M_Structure_0.geometry} material={materials.M_Structure} />
                  <mesh geometry={nodes.Plane_1_Employee_0.geometry} material={materials.Employee} position={[274.2, 359.6, 21.4]} rotation={[Math.PI / 2, 0, 0]} scale={[0.33, 0.146, 0.139]} />
                </group>
                <group position={[3564.394, 964.017, -7154.007]}>
                  <mesh geometry={nodes.door_1_M_Structure_0.geometry} material={materials.M_Structure} position={[-434.6, -213.7, 1164.605]} />
                  <mesh geometry={nodes.door_2_M_Structure_0.geometry} material={materials.M_Structure} position={[436.263, -213.7, 1148.267]} />
                </group>
              </group>
              <mesh geometry={nodes.restroom_wall_M_Structure_0.geometry} material={materials.M_Structure} />
            </group>
            <group position={[5164.481, 2090, -6223.287]} rotation={[0, Math.PI / 2, 0]} scale={[148.519, 38.018, 1.697]}>
              <group position={[-20.686, -18.708, -56.726]} rotation={[0, -Math.PI / 2, 0]} scale={[0.589, 0.026, 0.007]}>
                <mesh geometry={nodes.Memento_M_Posters_0.geometry} material={materials.M_Posters} position={[0, 0, -1117.115]} scale={[0.435, 16.24, 19.998]} />
                <mesh geometry={nodes.RussianDoll_M_Posters_0.geometry} material={materials.M_Posters} position={[0, 0, 1015.594]} scale={[0.435, 16.24, 19.998]} />
              </group>
              <mesh geometry={nodes._2poster_wall_M_Structure_0.geometry} material={materials.M_Structure} />
            </group>
            <mesh geometry={nodes.stair_wall1_M_Structure_0.geometry} material={materials.M_Structure} position={[-3685.769, 2494, -4458.793]} rotation={[0, Math.PI / 2, 0]} scale={[31.758, 45.832, 2.656]} />
            <mesh geometry={nodes.stair_wall2_M_Structure_0.geometry} material={materials.M_Structure} position={[-5385.272, 2494, -4458.793]} rotation={[0, Math.PI / 2, 0]} scale={[31.758, 45.832, 2.656]} />
            <mesh geometry={nodes.stair_ceiling_M_Structure_0.geometry} material={materials.M_Structure} position={[-4517.295, 2381.295, -4458.793]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[31.758, 17.962, 3.668]} />
            <mesh geometry={nodes.corner_wall_M_Structure_0.geometry} material={materials.M_Structure} position={[-5786.486, 2090, -2931.513]} rotation={[0, Math.PI / 2, 0]} scale={[148.519, 38.018, 4.036]} />
            <mesh geometry={nodes.longwall_M_Structure_0.geometry} material={materials.M_Structure} position={[309.005, 2113, 5160.546]} scale={[148.519, 38.4, 4.036]} />
            <mesh geometry={nodes.ground_stair_wall_M_Structure_0.geometry} material={materials.M_Structure} position={[7249.703, 2090, 3305.537]} scale={[40.627, 38.018, 4.036]} />
          </group>
          <group position={[818.601, 2910, 0]} scale={[137.807, 1.4, 557.066]}>
            <mesh geometry={nodes.Middle_M_Structure_0.geometry} material={materials.M_Structure} />
            <mesh geometry={nodes.pCube24_M_Stairs_0.geometry} material={materials.M_Stairs} position={[-12.064, -353, 15.985]} scale={[0.006, 0.6, 0.002]} />
            <mesh geometry={nodes.pCube22_6_M_Stairs_0.geometry} material={materials.M_Stairs} position={[-12.239, -353, -1.29]} scale={[0.006, 0.6, 0.002]} />
            <mesh geometry={nodes.pCube23_M_Stairs_0.geometry} material={materials.M_Stairs} position={[-12.064, -353, -16.407]} scale={[0.006, 0.6, 0.002]} />
            <mesh geometry={nodes.pCube25_M_Stairs_0.geometry} material={materials.M_Stairs} position={[-24.586, -175.051, 0]} scale={[0.005, 0.714, 0.61]} />
          </group>
          <group position={[818.601, -273.225, 0]} scale={[72.998, 5.848, 313.207]}>
            <group position={[-11.214, 46.725, 0]} scale={[0.014, 0.171, 0.003]}>
              <mesh geometry={nodes.pCube8_M_Stairs_0.geometry} material={materials.M_Stairs} position={[-2325.371, 1323.937, -750.306]} scale={[3.359, 28.115, 3.774]} />
              <mesh geometry={nodes.pCube9_6_M_Stairs_0.geometry} material={materials.M_Stairs} position={[-2325.371, 1323.937, 3174.557]} scale={[3.359, 28.115, 3.774]} />
              <mesh geometry={nodes.pCube10_M_Stairs_0.geometry} material={materials.M_Stairs} position={[-2325.371, 1323.937, 7099.419]} scale={[3.359, 28.115, 3.774]} />
              <mesh geometry={nodes.pCube11_6_M_Stairs_0.geometry} material={materials.M_Stairs} position={[-2325.371, 1323.937, 11024.283]} scale={[3.359, 28.115, 3.774]} />
              <mesh geometry={nodes.pCube12_M_Stairs_0.geometry} material={materials.M_Stairs} position={[-2325.371, 1323.937, -4453.638]} scale={[3.359, 28.115, 3.774]} />
              <mesh geometry={nodes.pCube13_M_Stairs_0.geometry} material={materials.M_Stairs} position={[-2325.371, 1323.937, -8378.501]} scale={[3.359, 28.115, 3.774]} />
              <mesh geometry={nodes.pCube14_M_Stairs_0.geometry} material={materials.M_Stairs} position={[-2325.371, 1323.937, -12303.364]} scale={[3.359, 28.115, 3.774]} />
              <mesh geometry={nodes.pCube15_M_Stairs_0.geometry} material={materials.M_Stairs} position={[-2325.371, 1630.562, 6897.979]} scale={[3.359, 4.511, 0.325]} />
              <mesh geometry={nodes.pCube16_M_Stairs_0.geometry} material={materials.M_Stairs} position={[-2325.371, 1630.562, -954.677]} scale={[3.359, 4.511, 0.325]} />
              <mesh geometry={nodes.pCube17_M_Stairs_0.geometry} material={materials.M_Stairs} position={[-2325.371, 1630.562, -8582.124]} scale={[3.359, 4.511, 0.325]} />
            </group>
            <group position={[-12.077, 271.092, 1.309]} scale={[0.014, 0.171, 0.003]}>
              <mesh geometry={nodes.polySurface158_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface159_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface160_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface161_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface162_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface163_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface164_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface165_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface166_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface167_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface168_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface169_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface170_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface171_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface172_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface173_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface174_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface175_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface176_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface177_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface178_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface179_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface180_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface181_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface182_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface183_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface184_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface185_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface186_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface187_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface188_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface189_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface190_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface191_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface192_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface193_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface194_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface195_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface196_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface197_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface198_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface199_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface200_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface201_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface202_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface203_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface204_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface205_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface206_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface207_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface208_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface209_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface210_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface211_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface212_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface213_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface214_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface215_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface216_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface217_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface218_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface219_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface220_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface221_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface222_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface223_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface224_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface225_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface226_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface227_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface228_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface229_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface230_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface231_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface232_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface233_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface234_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface235_M_Stairs_0.geometry} material={materials.M_Stairs} position={[-846.258, 214.254, 2149.179]} />
              <mesh geometry={nodes.polySurface236_M_Stairs_0.geometry} material={materials.M_Stairs} position={[-846.258, 1802.289, 2205.706]} />
              <mesh geometry={nodes.polySurface237_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface238_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface239_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface240_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface241_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -1349.766, -887.778]} />
              <mesh geometry={nodes.polySurface243_M_Stairs_0.geometry} material={materials.M_Stairs} position={[-850.241, -152.898, 790.641]} />
              <mesh geometry={nodes.polySurface244_M_Stairs_0.geometry} material={materials.M_Stairs} position={[-846.258, 101.135, 1703.127]} />
              <mesh geometry={nodes.polySurface245_M_Stairs_0.geometry} material={materials.M_Stairs} position={[-846.258, 1402.971, 1695.862]} />
              <mesh geometry={nodes.polySurface246_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -803.989, -290.626]} />
              <mesh geometry={nodes.polySurface247_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -803.989, -290.626]} />
              <mesh geometry={nodes.polySurface248_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -803.989, -290.626]} />
              <mesh geometry={nodes.polySurface249_M_Stairs_0.geometry} material={materials.M_Stairs} position={[53.742, -803.989, -290.626]} />
              <mesh geometry={nodes.polySurface250_M_Stairs_0.geometry} material={materials.M_Stairs} position={[-1524.918, 1819.593, 1853.515]} scale={[1, 1.056, 1]} />
              <mesh geometry={nodes.polySurface251_M_Stairs_0.geometry} material={materials.M_Stairs} position={[-159.613, 1819.593, 1853.515]} scale={[1, 1.056, 1]} />
              <mesh geometry={nodes.polySurface252_M_Stairs_0.geometry} material={materials.M_Stairs} position={[-1524.918, 1953.735, 1996.367]} scale={[1, 1.056, 1]} />
              <mesh geometry={nodes.polySurface253_M_Stairs_0.geometry} material={materials.M_Stairs} position={[-159.613, 1953.735, 1996.367]} scale={[1, 1.056, 1]} />
              <mesh geometry={nodes.polySurface254_M_Stairs_0.geometry} material={materials.M_Stairs} position={[-1524.918, 2108.782, 2165.351]} scale={[1, 1.056, 1]} />
              <mesh geometry={nodes.polySurface255_M_Stairs_0.geometry} material={materials.M_Stairs} position={[-159.613, 2108.782, 2165.351]} scale={[1, 1.056, 1]} />
            </group>
            <mesh geometry={nodes.floor_M_Structure_0.geometry} material={materials.M_Structure} />
          </group>
          <group position={[1325.834, 1286.481, -49.409]} scale={[2.954, 12.506, 313.207]}>
            <group position={[-448.798, -96.681, 0.158]} scale={[0.339, 0.08, 0.003]}>
              <mesh geometry={nodes.sign_1_M_Posters_0.geometry} material={materials.M_Posters} position={[1164.105, 1687.532, -7037.57]} scale={[0.435, 5.183, 19.998]} />
              <mesh geometry={nodes.Triangle_1_M_Posters_0.geometry} material={materials.M_Posters} position={[1164.105, 1164.306, -12512.702]} scale={[0.435, 16.24, 19.998]} />
              <mesh geometry={nodes.HappyDeathDay_M_Posters_0.geometry} material={materials.M_Posters} position={[1164.105, 1164.306, -10379.992]} scale={[0.435, 16.24, 19.998]} />
              <mesh geometry={nodes.Inception_M_Posters_0.geometry} material={materials.M_Posters} position={[1164.105, 1164.306, -3721.702]} scale={[0.435, 16.24, 19.998]} />
              <mesh geometry={nodes.Memento_1_M_Posters_0.geometry} material={materials.M_Posters} position={[1164.105, 1164.306, -1588.993]} scale={[0.435, 16.24, 19.998]} />
              <mesh geometry={nodes.SourceCode_M_Posters_0.geometry} material={materials.M_Posters} position={[1164.105, 1164.306, 3909.95]} scale={[0.435, 16.24, 19.998]} />
              <mesh geometry={nodes.GroundhogDay_M_Posters_0.geometry} material={materials.M_Posters} position={[1164.105, 1164.306, 6042.659]} scale={[0.435, 16.24, 19.998]} />
              <mesh geometry={nodes.sign2_M_Posters_0.geometry} material={materials.M_Posters} position={[1164.105, 1687.532, 10836.599]} scale={[0.435, 5.183, 19.998]} />
            </group>
            <mesh geometry={nodes.long_wall_M_Structure_0.geometry} material={materials.M_Structure} />
          </group>
          <mesh geometry={nodes.pCube3_7_M_Structure_0.geometry} material={materials.M_Structure} position={[-758.635, 2429, -14847.307]} rotation={[0, Math.PI / 2, 0]} scale={[3.228, 13.862, 41.187]} />
          <mesh geometry={nodes.pCube5_7_M_Structure_0.geometry} material={materials.M_Structure} position={[-758.635, 2078, 14816.278]} rotation={[0, Math.PI / 2, 0]} scale={[3.228, 12.506, 41.187]} />
        </group>
        <mesh geometry={nodes.Ticket_Machine_M_TicketMachine_0.geometry} material={materials.M_TicketMachine} position={[7466.564, 2129.401, 4585.129]} />
        <mesh geometry={nodes.Ticket_Machine1_M_TicketMachine_0.geometry} material={materials.M_TicketMachine} position={[7466.564, 2129.401, 5524.454]} />
        <group position={[-5691.436, -509.599, -12303.545]} scale={1.265}>
          <mesh geometry={nodes.pCube1_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1408.661, -881.019, 0]} scale={[4.508, 16.728, 74.303]} />
          <mesh geometry={nodes.pCube3_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-856.258, 1050.13, 0]} scale={[1.205, 0.96, 75.124]} />
          <mesh geometry={nodes.pCube4_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1144.159, 6.504, 0]} scale={[0.856, 0.683, 75.124]} />
          <mesh geometry={nodes.pCube5_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1138.433, 594.57, 7.706]} />
          <mesh geometry={nodes.pCube6_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1352.463, -453.212, 1178.893]} />
          <mesh geometry={nodes.pCube7_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1000.983, 945.524, 0]} scale={[0.467, 0.372, 75.124]} />
          <mesh geometry={nodes.pCube9_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1408.661, -1630.271, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[4.508, 23.049, 74.303]} />
          <mesh geometry={nodes.pCube11_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[489.419, -1453.872, 0]} />
          <mesh geometry={nodes.pCube22_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-260.57, -1402.583, 0]} />
          <mesh geometry={nodes.pCube64_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-748.915, 1094.521, 1378.265]} rotation={[0, 0, -0.803]} scale={[1.698, 5.375, 3.305]} />
          <mesh geometry={nodes.pCube66_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1144.159, 6.504, 2994.882]} scale={[0.856, 0.683, 75.124]} />
          <mesh geometry={nodes.pCube67_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-566.069, -1257.657, 39.512]} />
          <mesh geometry={nodes.pCylinder1_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[60.464, 98.017, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[16.939, 36.936, 16.939]} />
          <mesh geometry={nodes.pCylinder4_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-874.623, 396.243, 0]} />
          <mesh geometry={nodes.polySurface745_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[491.485, -1374.852, -25.36]} />
        </group>
        <group position={[-5691.436, -509.599, -21643.545]} scale={1.265}>
          <mesh geometry={nodes.pCube1_1_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1408.661, -881.019, 0]} scale={[4.508, 16.728, 74.303]} />
          <mesh geometry={nodes.pCube3_1_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-856.258, 1050.13, 0]} scale={[1.205, 0.96, 75.124]} />
          <mesh geometry={nodes.pCube4_1_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1144.159, 6.504, 0]} scale={[0.856, 0.683, 75.124]} />
          <mesh geometry={nodes.pCube5_1_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1138.433, 594.57, 7.706]} />
          <mesh geometry={nodes.pCube6_1_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1352.463, -453.212, 1178.893]} />
          <mesh geometry={nodes.pCube7_1_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1000.983, 945.524, 0]} scale={[0.467, 0.372, 75.124]} />
          <mesh geometry={nodes.pCube9_1_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1408.661, -1630.271, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[4.508, 23.049, 74.303]} />
          <mesh geometry={nodes.pCube11_1_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[489.419, -1453.872, 0]} />
          <mesh geometry={nodes.pCube22_1_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-260.57, -1402.583, 0]} />
          <mesh geometry={nodes.pCube64_1_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-748.915, 1094.521, 1378.265]} rotation={[0, 0, -0.803]} scale={[1.698, 5.375, 3.305]} />
          <mesh geometry={nodes.pCube66_1_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1144.159, 6.504, 2994.882]} scale={[0.856, 0.683, 75.124]} />
          <mesh geometry={nodes.pCube67_1_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-566.069, -1257.657, 39.512]} />
          <mesh geometry={nodes.pCylinder1_1_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[60.464, 98.017, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[16.939, 36.936, 16.939]} />
          <mesh geometry={nodes.pCylinder4_1_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-874.623, 396.243, 0]} />
          <mesh geometry={nodes.polySurface745_1_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[491.485, -1374.852, -25.36]} />
        </group>
        <group position={[-5691.436, -509.599, 15716.455]} scale={1.265}>
          <mesh geometry={nodes.pCube1_2_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1408.661, -881.019, 0]} scale={[4.508, 16.728, 74.303]} />
          <mesh geometry={nodes.pCube3_2_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-856.258, 1050.13, 0]} scale={[1.205, 0.96, 75.124]} />
          <mesh geometry={nodes.pCube4_2_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1144.159, 6.504, 0]} scale={[0.856, 0.683, 75.124]} />
          <mesh geometry={nodes.pCube5_2_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1138.433, 594.57, 7.706]} />
          <mesh geometry={nodes.pCube6_2_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1352.463, -453.212, 1178.893]} />
          <mesh geometry={nodes.pCube7_2_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1000.983, 945.524, 0]} scale={[0.467, 0.372, 75.124]} />
          <mesh geometry={nodes.pCube9_2_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1408.661, -1630.271, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[4.508, 23.049, 74.303]} />
          <mesh geometry={nodes.pCube11_2_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[489.419, -1453.872, 0]} />
          <mesh geometry={nodes.pCube22_2_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-260.57, -1402.583, 0]} />
          <mesh geometry={nodes.pCube64_2_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-748.915, 1094.521, 1378.265]} rotation={[0, 0, -0.803]} scale={[1.698, 5.375, 3.305]} />
          <mesh geometry={nodes.pCube66_2_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1144.159, 6.504, 2994.882]} scale={[0.856, 0.683, 75.124]} />
          <mesh geometry={nodes.pCube67_2_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-566.069, -1257.657, 39.512]} />
          <mesh geometry={nodes.pCylinder1_2_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[60.464, 98.017, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[16.939, 36.936, 16.939]} />
          <mesh geometry={nodes.pCylinder4_2_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-874.623, 396.243, 0]} />
          <mesh geometry={nodes.polySurface745_2_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[491.485, -1374.852, -25.36]} />
        </group>
        <group position={[-5691.436, -509.599, 25056.455]} scale={1.265}>
          <mesh geometry={nodes.pCube1_3_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1408.661, -881.019, 0]} scale={[4.508, 16.728, 74.303]} />
          <mesh geometry={nodes.pCube3_3_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-856.258, 1050.13, 0]} scale={[1.205, 0.96, 75.124]} />
          <mesh geometry={nodes.pCube4_3_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1144.159, 6.504, 0]} scale={[0.856, 0.683, 75.124]} />
          <mesh geometry={nodes.pCube5_3_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1138.433, 594.57, 7.706]} />
          <mesh geometry={nodes.pCube6_3_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1352.463, -453.212, 1178.893]} />
          <mesh geometry={nodes.pCube7_3_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1000.983, 945.524, 0]} scale={[0.467, 0.372, 75.124]} />
          <mesh geometry={nodes.pCube9_3_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1408.661, -1630.271, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[4.508, 23.049, 74.303]} />
          <mesh geometry={nodes.pCube11_3_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[489.419, -1453.872, 0]} />
          <mesh geometry={nodes.pCube22_3_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-260.57, -1402.583, 0]} />
          <mesh geometry={nodes.pCube64_3_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-748.915, 1094.521, 1378.265]} rotation={[0, 0, -0.803]} scale={[1.698, 5.375, 3.305]} />
          <mesh geometry={nodes.pCube66_3_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1144.159, 6.504, 2994.882]} scale={[0.856, 0.683, 75.124]} />
          <mesh geometry={nodes.pCube67_3_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-566.069, -1257.657, 39.512]} />
          <mesh geometry={nodes.pCylinder1_3_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[60.464, 98.017, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[16.939, 36.936, 16.939]} />
          <mesh geometry={nodes.pCylinder4_3_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-874.623, 396.243, 0]} />
          <mesh geometry={nodes.polySurface745_3_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[491.485, -1374.852, -25.36]} />
        </group>
        <group position={[-5691.436, -509.599, -2953.546]} scale={1.265}>
          <mesh geometry={nodes.pCube1_4_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1408.661, -881.019, 0]} scale={[4.508, 16.728, 74.303]} />
          <mesh geometry={nodes.pCube3_4_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-856.258, 1050.13, 0]} scale={[1.205, 0.96, 75.124]} />
          <mesh geometry={nodes.pCube4_4_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1144.159, 6.504, 0]} scale={[0.856, 0.683, 75.124]} />
          <mesh geometry={nodes.pCube5_4_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1138.433, 594.57, 7.706]} />
          <mesh geometry={nodes.pCube6_4_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1352.463, -453.212, 1178.893]} />
          <mesh geometry={nodes.pCube7_4_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1000.983, 945.524, 0]} scale={[0.467, 0.372, 75.124]} />
          <mesh geometry={nodes.pCube9_4_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1408.661, -1630.271, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[4.508, 23.049, 74.303]} />
          <mesh geometry={nodes.pCube11_4_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[489.419, -1453.872, 0]} />
          <mesh geometry={nodes.pCube22_4_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-260.57, -1402.583, 0]} />
          <mesh geometry={nodes.pCube64_4_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-748.915, 1094.521, 1378.265]} rotation={[0, 0, -0.803]} scale={[1.698, 5.375, 3.305]} />
          <mesh geometry={nodes.pCube66_4_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1144.159, 6.504, 2994.882]} scale={[0.856, 0.683, 75.124]} />
          <mesh geometry={nodes.pCube67_4_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-566.069, -1257.657, 39.512]} />
          <mesh geometry={nodes.pCylinder1_4_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[60.464, 98.017, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[16.939, 36.936, 16.939]} />
          <mesh geometry={nodes.pCylinder4_4_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-874.623, 396.243, 0]} />
          <mesh geometry={nodes.polySurface745_4_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[491.485, -1374.852, -25.36]} />
        </group>
        <group position={[-5691.436, -509.599, 6386.454]} scale={1.265}>
          <mesh geometry={nodes.pCube1_5_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1408.661, -881.019, 0]} scale={[4.508, 16.728, 74.303]} />
          <mesh geometry={nodes.pCube3_5_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-856.258, 1050.13, 0]} scale={[1.205, 0.96, 75.124]} />
          <mesh geometry={nodes.pCube4_5_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1144.159, 6.504, 0]} scale={[0.856, 0.683, 75.124]} />
          <mesh geometry={nodes.pCube5_5_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1138.433, 594.57, 7.706]} />
          <mesh geometry={nodes.pCube6_5_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1352.463, -453.212, 1178.893]} />
          <mesh geometry={nodes.pCube7_5_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1000.983, 945.524, 0]} scale={[0.467, 0.372, 75.124]} />
          <mesh geometry={nodes.pCube9_5_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1408.661, -1630.271, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[4.508, 23.049, 74.303]} />
          <mesh geometry={nodes.pCube11_5_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[489.419, -1453.872, 0]} />
          <mesh geometry={nodes.pCube22_5_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-260.57, -1402.583, 0]} />
          <mesh geometry={nodes.pCube64_5_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-748.915, 1094.521, 1378.265]} rotation={[0, 0, -0.803]} scale={[1.698, 5.375, 3.305]} />
          <mesh geometry={nodes.pCube66_5_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1144.159, 6.504, 2994.882]} scale={[0.856, 0.683, 75.124]} />
          <mesh geometry={nodes.pCube67_5_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-566.069, -1257.657, 39.512]} />
          <mesh geometry={nodes.pCylinder1_5_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[60.464, 98.017, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[16.939, 36.936, 16.939]} />
          <mesh geometry={nodes.pCylinder4_5_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-874.623, 396.243, 0]} />
          <mesh geometry={nodes.polySurface745_5_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[491.485, -1374.852, -25.36]} />
        </group>
        <group position={[-5161.436, -509.599, -22393.545]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.265}>
          <mesh geometry={nodes.pCube1_6_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1408.661, -881.019, 0]} scale={[4.508, 16.728, 74.303]} />
          <mesh geometry={nodes.pCube3_6_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-856.258, 1050.13, 0]} scale={[1.205, 0.96, 75.124]} />
          <mesh geometry={nodes.pCube4_6_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1144.159, 6.504, 0]} scale={[0.856, 0.683, 75.124]} />
          <mesh geometry={nodes.pCube5_6_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1138.433, 594.57, 7.706]} />
          <mesh geometry={nodes.pCube6_6_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1352.463, -453.212, 1178.893]} />
          <mesh geometry={nodes.pCube7_6_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1000.983, 945.524, 0]} scale={[0.467, 0.372, 75.124]} />
          <mesh geometry={nodes.pCube64_6_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-748.915, 1094.521, 1378.265]} rotation={[0, 0, -0.803]} scale={[1.698, 5.375, 3.305]} />
          <mesh geometry={nodes.pCube66_6_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1144.159, 6.504, 2994.882]} scale={[0.856, 0.683, 75.124]} />
          <mesh geometry={nodes.pCylinder1_6_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[60.464, 98.017, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[16.939, 36.936, 16.939]} />
          <mesh geometry={nodes.pCylinder4_6_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-874.623, 396.243, 0]} />
        </group>
        <group position={[-5161.436, -509.599, 26106.451]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.265}>
          <mesh geometry={nodes.pCube1_7_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1408.661, -881.019, 0]} scale={[4.508, 16.728, 74.303]} />
          <mesh geometry={nodes.pCube3_8_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-856.258, 1050.13, 0]} scale={[1.205, 0.96, 75.124]} />
          <mesh geometry={nodes.pCube4_7_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1144.159, 6.504, 0]} scale={[0.856, 0.683, 75.124]} />
          <mesh geometry={nodes.pCube5_8_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1138.433, 594.57, 7.706]} />
          <mesh geometry={nodes.pCube6_7_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1352.463, -453.212, 1178.893]} />
          <mesh geometry={nodes.pCube7_7_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1000.983, 945.524, 0]} scale={[0.467, 0.372, 75.124]} />
          <mesh geometry={nodes.pCube64_7_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-748.915, 1094.521, 1378.265]} rotation={[0, 0, -0.803]} scale={[1.698, 5.375, 3.305]} />
          <mesh geometry={nodes.pCube66_7_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1144.159, 6.504, 2994.882]} scale={[0.856, 0.683, 75.124]} />
          <mesh geometry={nodes.pCylinder1_7_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[60.464, 98.017, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[16.939, 36.936, 16.939]} />
          <mesh geometry={nodes.pCylinder4_7_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-874.623, 396.243, 0]} />
        </group>
        <group position={[-5161.436, -509.599, 16766.453]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.265}>
          <mesh geometry={nodes.pCube1_8_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1408.661, -881.019, 0]} scale={[4.508, 16.728, 74.303]} />
          <mesh geometry={nodes.pCube3_9_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-856.258, 1050.13, 0]} scale={[1.205, 0.96, 75.124]} />
          <mesh geometry={nodes.pCube4_8_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1144.159, 6.504, 0]} scale={[0.856, 0.683, 75.124]} />
          <mesh geometry={nodes.pCube5_9_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1138.433, 594.57, 7.706]} />
          <mesh geometry={nodes.pCube6_8_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1352.463, -453.212, 1178.893]} />
          <mesh geometry={nodes.pCube7_8_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1000.983, 945.524, 0]} scale={[0.467, 0.372, 75.124]} />
          <mesh geometry={nodes.pCube64_8_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-748.915, 1094.521, 1378.265]} rotation={[0, 0, -0.803]} scale={[1.698, 5.375, 3.305]} />
          <mesh geometry={nodes.pCube66_8_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-1144.159, 6.504, 2994.882]} scale={[0.856, 0.683, 75.124]} />
          <mesh geometry={nodes.pCylinder1_8_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[60.464, 98.017, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[16.939, 36.936, 16.939]} />
          <mesh geometry={nodes.pCylinder4_8_M_Tunnel_0.geometry} material={materials.M_Tunnel} position={[-874.623, 396.243, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/subway.glb')
